version: '3'
services:
  mysql_master:
    restart: always
    image: mysql:5.7
    container_name: mysql_master
    hostname: mysql_master
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql_master/mysql_master.cnf:/etc/mysql/my.cnf
      - ./mysql_master/data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.18.0.105
  filerun:
    image: afian/filerun
    container_name: filerun
    ports:
      - 8080:80
    environment:
      FR_DB_HOST: mysql_master
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: root
      FR_DB_PASS: 123456
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    volumes:
      - ./filerun/html:/var/www/html
      - ./filerun/user-files:/user-files
    depends_on:
      - mysql_master
    networks:
      default:
        ipv4_address: 172.18.0.235
networks:
  default:
    external:
       name: bridge_compose
