version: '3'
services:
  nginx:
    restart: always
    image: nginx:stable
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./cert:/etc/nginx/cert
