version: '3'
services:
  jenkins:
    restart: always
    image: "jenkins/jenkins"
    container_name: jenkins
    hostname: jenkins
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - jenkins:/var/jenkins_home
      - /etc/localtime:/etc/localtime
