version: '3'
services:
  online:
    image: libreoffice/online
    container_name: libreoffice
    hostname: libreoffice
    environment:
      TZ: Asia/Shanghai
      domain: ${NEXTCLOUD_DOMAIN}
      username: ${LO_ONLINE_USERNAME}
      password: ${LO_ONLINE_PASSWORD}
      extra_params: ${LO_ONLINE_EXTRA_PARAMS}
      DONT_GEN_SSL_CERT: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - MKNOD
    ports:
      - 9980:9980
    restart:
      unless-stopped