version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:latest
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cluster-logs/nacos1:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
      - 9555:9555
    env_file:
      - ./env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql
    networks:
      default:
        ipv4_address: 172.18.0.208
  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:latest
    container_name: nacos2
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cluster-logs/nacos2:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8849:8848
    env_file:
      - ./env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql
    networks:
      default:
        ipv4_address: 172.18.0.209
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:latest
    container_name: nacos3
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cluster-logs/nacos3:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8850:8848
    env_file:
      - ./env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql
    networks:
      default:
        ipv4_address: 172.18.0.210
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:5.7
    env_file:
      - ./env/mysql.env
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      default:
        ipv4_address: 172.18.0.105
networks:
  default:
    external:
       name: bridge_compose