version: '3'
services:
  zoo1:
    restart: always
    image: zookeeper:3.5
    container_name: zoo1
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/zookeeper/zoo1/data:/data
      - /usr/local/zookeeper/zoo1/datalog:/datalog
    networks:
      default:
        ipv4_address: 172.18.0.201
  zoo2:
    restart: always
    image: zookeeper:3.5
    container_name: zoo2
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/zookeeper/zoo2/data:/data
      - /usr/local/zookeeper/zoo2/datalog:/datalog
    networks:
      default:
        ipv4_address: 172.18.0.202
  zoo3:
    restart: always
    image: zookeeper:3.5
    container_name: zoo3
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/zookeeper/zoo3/data:/data
      - /usr/local/zookeeper/zoo3/datalog:/datalog
    networks:
      default:
        ipv4_address: 172.18.0.203
  kafka1:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka1
    hostname: kafka1
    ports:
      - 9091:9092
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.18.0.204
  kafka2:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka2
    hostname: kafka2
    ports:
      - 9092:9092
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.18.0.205
  kafka3:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka3
    hostname: kafka3
    ports:
      - 9093:9092
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.18.0.206
  kafka-manager:
    restart: always
    # image: sheepkiller/kafka-manager
    image: hlebalbau/kafka-manager
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - 9000:9000
    environment:
      TZ: Asia/Shanghai
      ZK_HOSTS: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKERS: kafka1:9091,kafka2:9092,kafka3:9093
      APPLICATION_SECRET: t5750
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      default:
        ipv4_address: 172.18.0.207
networks:
  default:
    external:
       name: bridge_compose