spring:
  application:
    name: dubbo-consumer
server:
  port: 8082
  context-path: /${spring.application.name}
management:
  port: 9092
dubbo:
  scan:
    basePackages: t5750.dubbo.service
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.100.163:2181?backup=192.168.100.164:2181,192.168.100.165:2181
    id: zookeeper-registry
logging:
  file: dubbo/logs/${spring.application.name}.log
  level:
    root: info