server:
  port: 8080
  context-path: /dubbo-consumer
spring:
  dubbo:
    application:
      name: dubbo-consumer
    registry:
      address: zookeeper://192.168.100.163:2181?backup=192.168.100.164:2182,192.168.100.165:2183
    scan: t5750.dubbo.service