version: '3'
services:
  kafka1:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka1
    hostname: kafka1
    ports:
      - 9091:9092
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.18.0.204
  kafka2:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka2
    hostname: kafka2
    ports:
      - 9092:9092
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.18.0.205
  kafka3:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka3
    hostname: kafka3
    ports:
      - 9093:9092
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.18.0.206
networks:
  default:
    external:
       name: bridge_compose