version: "3"
services:
  mosquitto:
    restart: always
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    hostname: mosquitto
    ports:
      - 8883:8883
      - 9001:9001
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - $PWD/data:/mosquitto/data
      - $PWD/log:/mosquitto/log
      - /etc/ssl:/etc/mosquitto/ssl
