version: '3'
services:
  mysql_master:
    restart: always
    image: mysql:5.7
    container_name: mysql_master
    hostname: mysql_master
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: replicas_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql_master/mysql_master.cnf:/etc/mysql/my.cnf
      - ./mysql_master/data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.18.0.105
  cat:
    image: rolesle/cat:0.0.1
    container_name: cat
    environment:
      - TZ=Asia/Shanghai
      # if you have your own mysql, config it here, and disable the 'mysql' config blow
      - MYSQL_URL=mysql_master # links will maintain /etc/hosts, just use 'container_name'
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWD=123456
      - MYSQL_SCHEMA=cat
      # 必须设置成你的机器IP地址
      # - SERVER_IP=YOUR IP
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # 默认127.0.0.1，可以修改为自己真实的服务器集群地址
      #- ./client.xml:/data/appdatas/cat/client.xml
      # 默认使用环境变量设置。可以启用本注解，并修改为自己的配置
#      - ./datasources.xml:/data/appdatas/cat/datasources.xml
    command: /bin/sh -c 'chmod +x /datasources.sh && /datasources.sh && catalina.sh run'
    depends_on:
      - mysql_master
    ports:
      - 8080:8080
      - 2280:2280
    networks:
      default:
        ipv4_address: 172.18.0.234
networks:
  default:
    external:
       name: bridge_compose
