version: '3'
services:
  loki:
    restart: always
    image: grafana/loki:2.4.0
    container_name: loki
    hostname: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        ipv4_address: 172.18.0.236
  promtail:
    restart: always
    image: grafana/promtail:2.4.0
    container_name: promtail
    hostname: promtail
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      default:
        ipv4_address: 172.18.0.237
  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/grafana:/var/lib/grafana
    networks:
      default:
        ipv4_address: 172.18.0.235
networks:
  default:
    external:
       name: bridge_compose
