version: '3'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    hostname: jenkins
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
    volumes:
      - $PWD/jenkins:/var/jenkins_home
      - /etc/localtime:/etc/localtime
