version: '3'
services:
  xxl-job:
    restart: always
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job
    hostname: xxl-job
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      PARAMS: "--spring.datasource.url=jdbc:mysql://mysql_master:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        --spring.datasource.username=root
        --spring.datasource.password=123456"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./xxl-job_tmp:/data/applogs
    external_links:
      - mysql_master
    networks:
      default:
        ipv4_address: 172.18.0.230
networks:
  default:
    external:
       name: bridge_compose
