version: '3'
services:
  konga-prepare:
    image: pantsel/konga
    command: "-c prepare -a postgres -u postgresql://kong:kong@db:5432/konga"
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_PG_DATABASE=konga
      - KONG_PG_PASSWORD=kong
    external_links:
      - db
    networks:
      default:
        ipv4_address: 172.18.0.218
  konga:
    image: pantsel/konga
    restart: always
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:kong@db:5432/konga
      NODE_ENV: production
    external_links:
      - db
    depends_on:
      - konga-prepare
    ports:
      - 1337:1337
    networks:
      default:
        ipv4_address: 172.18.0.219
networks:
  default:
    external:
       name: bridge_compose