server:
  port: 8052
  context-path: /spring-boot-sso-app-bar
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: foo
      clientSecret: bar
      accessTokenUri: http://localhost:8050/spring-boot-sso-server/oauth/token
      userAuthorizationUri: http://localhost:8050/spring-boot-sso-server/oauth/authorize
    resource:
      userInfoUri: http://localhost:8050/spring-boot-sso-server/user/me