version: '3'
services:
  homeassistant:
    restart: unless-stopped
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    ports:
      - 8123:8090
    environment:
      TZ: Asia/Shanghai
    volumes:
      #- /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
