version: '3'
services:
  pgmaster:
    restart: always
    image: postgres:11.9
    container_name: pgmaster
    hostname: pgmaster
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./pgmaster:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.18.0.100
  tb:
    restart: always
    image: thingsboard/tb-postgres
    container_name: tb
    hostname: tb
    ports:
      - 9090:9090
      - 1883:1883
      - 5683:5683/udp
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgmaster:5432/thingsboard
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
    networks:
      default:
        ipv4_address: 172.18.0.220
networks:
  default:
    external:
       name: bridge_compose