version: '3'
services:
  mytb:
    restart: always
    image: thingsboard/tb-postgres:3.1.1
    container_name: mytb
    hostname: mytb
    ports:
      - 8080:9090
      - 1883:1883
      - 5683:5683/udp
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgmaster:5432/thingsboard
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
