#!/bin/bash
printf '%s\n' "`date "+%Y-%m-%d %H:%M:%S"`"
printf '%s\n' "`date "+%Y%m%d%H%M%S"`"
printf '%s\n' "`date "+%Y-%m-%d"`"
printf '%s\n' "`date "+%H:%M:%S"`"
printf '%s\n' "`date -d today` -> today"
printf '%s\n' "`date -d now` -> now"
printf '%s\n' "`date -d tomorrow` -> tomorrow"
printf '%s\n' "`date -d yesterday` -> yesterday"
printf '%s\n' "`date +%Y%m%d --date="+1 day"`"
printf '%s\n' "`date +%Y%m%d --date="-1 day"`"
printf '%s\n' "`date +%Y%m%d --date="-1 month"`"
printf '%s\n' "`date +%Y%m%d --date="+1 month"`"
printf '%s\n' "`date +%Y%m%d --date="-1 year"`"
printf '%s\n' "`date +%Y%m%d --date="+1 year"`"