server:
  port: 18086
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: spring-cloud-dubbo-server

provider:
  application:
    name: spring-cloud-dubbo-server