version: '3'
services:
  couchbase:
    restart: always
    image: couchbase/server
    container_name: couchbase
    hostname: couchbase
    ports:
      - 8091-8094:8091-8094
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./couchbase:/opt/couchbase/var
