version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db:/data/db
      - ./log:/var/log/mongodb
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      default:
        ipv4_address: 172.18.0.131
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      TZ: Asia/Shanghai
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        ipv4_address: 172.18.0.134
networks:
  default:
    external:
       name: bridge_compose