version: '3'
services:
  mysql_master:
    restart: always
    image: mysql:5.7
    container_name: mysql_master
    hostname: mysql_master
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: replicas_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql_master/mysql_master.cnf:/etc/mysql/my.cnf
      - ./mysql_master/data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.18.0.105
  mysql_slave:
    restart: always
    image: mysql:5.7
    container_name: mysql_slave
    hostname: mysql_slave
    ports:
      - 3307:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: replicas_db
    depends_on:
      - mysql_master
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql_slave/mysql_slave.cnf:/etc/mysql/my.cnf
      - ./mysql_slave/data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.18.0.106
networks:
  default:
    external:
       name: bridge_compose