version: '3'
services:
  redis1:
    restart: always
    image: redis:5
    container_name: redis1
    hostname: redis1
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/redis1/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
