CREATE OR REPLACE PROCEDURE DB2INST1.PRO_SAVE_UPDATE_ORDERFORMGIFT
(IN in_sc_id BIGINT,
IN in_promotion_id BIGINT,
INOUT inout_issuccess INT) -- 0：异常；1：全部更新成功
	DYNAMIC RESULT SETS 1
LANGUAGE SQL
MODIFIES SQL DATA
SPECIFIC PRO_SAVE_UPDATE_ORDERFORMGIFT
-- #######################################################################
-- # 遍历PROMOTIONLEVEL，处理订单满赠表，新增或合并订单赠品
-- #######################################################################
BEGIN ATOMIC
	DECLARE v_promotion_ids VARCHAR(200);
	DECLARE EXIT HANDLER FOR SQLEXCEPTION,SQLWARNING set inout_issuccess = 0; -- 异常处理

--start 遍历LAKECLOUD_PROMOTIONLEVEL中的gift
FOR loop_gift AS SELECT T1.GOODS_ID,T1.PROMOTION_ID,T2.ID AS OFG_ID,T2.COUNT AS OFG_COUNT,T2.PROMOTION_IDS,T2.DELETESTATUS FROM DB2INST1.LAKECLOUD_PROMOTIONLEVEL T1 LEFT JOIN (SELECT ID,COUNT,PROMOTION_IDS,DELETESTATUS,GOODS_ID FROM DB2INST1.LAKECLOUD_ORDERFORMGIFT WHERE DELETESTATUS<>1 AND SC_ID=in_sc_id) T2 ON T1.GOODS_ID=T2.GOODS_ID WHERE T1.DELETESTATUS=0 AND T1.PRODUCT='gift' AND T1.PROMOTION_ID=in_promotion_id
DO
	IF loop_gift.OFG_ID IS NULL THEN
		INSERT INTO LAKECLOUD_ORDERFORMGIFT(ADDTIME,DELETESTATUS,COUNT,GOODS_ID,SC_ID,PROMOTION_IDS) VALUES(CURRENT TIMESTAMP,0,1,loop_gift.GOODS_ID,in_sc_id,loop_gift.PROMOTION_ID);
	ELSE
		SET v_promotion_ids = loop_gift.PROMOTION_IDS || ',' || loop_gift.PROMOTION_ID;
		UPDATE LAKECLOUD_ORDERFORMGIFT SET COUNT = loop_gift.OFG_COUNT + 1 , UPDATETIME = CURRENT TIMESTAMP , PROMOTION_IDS = v_promotion_ids WHERE ID = loop_gift.OFG_ID;
	END IF;
END FOR;
--end 遍历LAKECLOUD_PROMOTIONLEVEL中的gift

	SET inout_issuccess = 1;

END