version: '3'
services:
  mysql:
    restart: always
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    command:
        - --default_authentication_plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
  wordpress:
    restart: always
    image: wordpress:latest
    container_name: wordpress
    hostname: wordpress
    ports:
      - 8000:80
    environment:
      TZ: Asia/Shanghai
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    depends_on:
       - mysql