server:
  port: 8081
  context-path: /activemq-consumer
spring:
  activemq:
    user: admin
    password: admin
    #broker-url: tcp://localhost:61616
    #broker-url: failover:(tcp://localhost:51511,tcp://localhost:51512,tcp://localhost:51513)
    broker-url: failover:(tcp://192.168.100.163:51511,tcp://192.168.100.164:51512,tcp://192.168.100.165:51513)
    pool:
      enabled: true
      max-connections: 10
  mail:
    host: smtp.163.com
    username: username@163.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

queueName: publish.queue
topicName: publish.topic
queueNameMail: mailqueue