#
# Function "FUN_DATE_ADD"
#

DROP FUNCTION IF EXISTS `FUN_DATE_ADD`;
CREATE FUNCTION `FUN_DATE_ADD`(STR_DATE VARCHAR(10), STR_INTERVAL INTEGER) RETURNS date
	BEGIN
		RETURN date_add(STR_DATE, INTERVAL STR_INTERVAL DAY);
	END;

#
# Function "FUN_NOW"
#

DROP FUNCTION IF EXISTS `FUN_NOW`;
CREATE FUNCTION `FUN_NOW`() RETURNS datetime
	BEGIN
		RETURN now();
	END;

#
# Function "FUN_SEQ"
#

DROP FUNCTION IF EXISTS `FUN_SEQ`;
CREATE FUNCTION `FUN_SEQ`(SEQ VARCHAR(50)) RETURNS bigint(20)
	BEGIN
		UPDATE SEQ_TABLE
		SET CURRENT_VALUE = CURRENT_VALUE + INCREMENT
		WHERE  SEQ_NAME=SEQ;
		RETURN FUN_SEQ_CURRENT_VALUE(SEQ);
	END;

#
# Function "FUN_SEQ_CURRENT_VALUE"
#

DROP FUNCTION IF EXISTS `FUN_SEQ_CURRENT_VALUE`;
CREATE FUNCTION `FUN_SEQ_CURRENT_VALUE`(SEQ VARCHAR(50)) RETURNS bigint(20)
	BEGIN
		DECLARE VALUE INTEGER;
		SET VALUE=0;
		SELECT CURRENT_VALUE INTO VALUE
		FROM SEQ_TABLE
		WHERE SEQ_NAME=SEQ;
		RETURN VALUE;
	END;

#
# Function "FUN_SEQ_SET_VALUE"
#

DROP FUNCTION IF EXISTS `FUN_SEQ_SET_VALUE`;
CREATE FUNCTION `FUN_SEQ_SET_VALUE`(SEQ VARCHAR(50), VALUE INTEGER) RETURNS bigint(20)
	BEGIN
		UPDATE SEQ_TABLE
		SET CURRENT_VALUE=VALUE
		WHERE SEQ_NAME=SEQ;
		RETURN FUN_SEQ_CURRENT_VALUE(SEQ);
	END;